repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff-format
        args: ["--config=pyproject.toml"]
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--config=pyproject.toml"]
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [
          "--explicit-package-bases",
          "--namespace-packages",
          "--python-version=3.12",
        ]
        files: "^(src/aider_mcp_server|tests)/"
        additional_dependencies: ["pydantic>=2.11.2"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        files: "\\.(c|cpp|h|hpp|pyx)$"
