# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install build dependencies
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Expose port if needed (not specified in MCP, so none)

# Run the MCP server
ENTRYPOINT ["aider-mcp-server"]
