[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aider-mcp-server"
version = "0.1.0"
description = "Aider MCP Server - Offload AI coding tasks to Aider"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "Aider Team"}
]
dependencies = [
    "aider-chat>=0.81.0",
    "boto3>=1.37.27",
    "google-cloud-aiplatform>=1.38.0",
    "mcp>=1.6.0",
    "pydantic>=2.11.2",
    "rich>=14.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio",
    "pytest-mock",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
pythonpath = ["src"]
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools]
package-dir = {"" = "src"}
