name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint_and_types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Install pre-commit hooks
        run: hatch -e dev run pre-commit install --install-hooks

      - name: Run pre-commit
        run: |
          hatch -e dev run pre-commit run --all-files
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Code is not properly formatted. Please run formatters locally before pushing."
            git diff
            exit 1
          fi

  test:
    needs: lint_and_types
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Run tests with coverage
        run: |
          hatch -e test run pytest --cov=src --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  test-compatibility:
    needs: lint_and_types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
        aider-version: ['0.83.0', '0.83.1', 'latest']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-mock pytest-timeout
        pip install -e .

    - name: Install specific aider version
      run: |
        if [ "${{ matrix.aider-version }}" = "latest" ]; then
          pip install aider-chat
        else
          pip install aider-chat==${{ matrix.aider-version }}
        fi

    - name: Run compatibility check script
      run: |
        python scripts/inspect_aider_params.py

    - name: Display aider version
      run: |
        python -c "import aider; print(f'Testing with aider version: {aider.__version__}')"

    - name: Run compatibility tests
      run: |
        pytest tests/compatibility/ -v

    - name: Run integration tests
      run: |
        pytest tests/ -v -m integration
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
